version: '3.7'

volumes:
    grafana_data: {}
    prometheus_data: {}

networks:
  yearn-exporter:

services:
  yearn-exporter-v1:
    build: .
    command: exporter_v1
    ports:
      - 8800:8800
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-v2:
    build: .
    command: exporter_v2
    ports:
      - 8801:8801
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-iearn:
    build: .
    command: exporter_iearn
    ports:
      - 8802:8802
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-ironbank:
    build: .
    command: exporter_ironbank
    ports:
      - 8803:8803
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-experimental:
    build: .
    command: exporter_experimental
    ports:
      - 8804:8804
    environment:
      - WEB3_INFURA_PROJECT_ID
      - ALCHEMY_URL
      - ETHERSCAN_TOKEN
      - SLEEP_SECONDS
    networks:
      - yearn-exporter
    restart: always

  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - yearn-exporter
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/yearn/tvl_vaults.json
      - GF_SERVER_ROOT_URL=https://yearn.vision
      - GF_RENDERING_SERVER_URL=http://renderer:8091/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - yearn-exporter
    restart: always

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8091:8091
    environment:
      - ENABLE_METRICS=true
      - HTTP_PORT=8091
    networks:
      - yearn-exporter
    restart: always

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    ports:
      - 9113:9113
    command:
      - '-nginx.scrape-uri'
      - 'https://yearn.vision/stub_status'
    networks:
      - yearn-exporter
    restart: always
